if (CMAKE_CL_64)
    set ( DIRECTXMESH_ARCH "x64" )
else()
    set ( DIRECTXMESH_ARCH "Win32" )
endif()

find_path( DIRECTXMESH_ROOT NAMES DirectXMesh.h )
    
find_library ( DIRECTXMESH_LIBRARY_RELEASE NAMES DirectXMesh PATHS ${DIRECTXMESH_ROOT}/Bin/*/${DIRECTXMESH_ARCH}/Release )
find_library ( DIRECTXMESH_LIBRARY_DEBUG NAMES DirectXMesh PATHS ${DIRECTXMESH_ROOT}/Bin/*/${DIRECTXMESH_ARCH}/Debug )
    
if (DIRECTXMESH_LIBRARY_RELEASE AND DIRECTXMESH_LIBRARY_DEBUG)
	set ( DIRECTXMESH_FOUND TRUE )
else ()
	set ( DIRECTXMESH_FOUND FALSE )
endif ()
    
if (DIRECTXMESH_FOUND)

    mark_as_advanced ( DIRECTXMESH_ROOT DIRECTXMESH_LIBRARY_RELEASE DIRECTXMESH_LIBRARY_DEBUG )
	
    set ( DIRECTXMESH_INCLUDE_DIR ${DIRECTXMESH_ROOT} CACHE STRING "" )
    set ( DIRECTXMESH_LIBRARY optimized ${DIRECTXMESH_LIBRARY_RELEASE} debug ${DIRECTXMESH_LIBRARY_DEBUG} CACHE STRING "")
	
elseif (DIRECTXMESH_FIND_REQUIRED)

	message ( FATAL_ERROR "Could not find DirectXMesh" )
	
endif()