if (CMAKE_CL_64)
    set ( DIRECTXTK_ARCH "x64" )
else()
    set ( DIRECTXTK_ARCH "Win32" )
endif()

find_path( DIRECTXTK_ROOT NAMES DirectXHelpers.h )
    
find_library ( DIRECTXTK_LIBRARY_RELEASE NAMES DirectXTK PATHS ${DIRECTXTK_ROOT}/Bin/*/${DIRECTXTK_ARCH}/Release )
find_library ( DIRECTXTK_LIBRARY_DEBUG NAMES DirectXTK PATHS ${DIRECTXTK_ROOT}/Bin/*/${DIRECTXTK_ARCH}/Debug )
    
if (DIRECTXTK_LIBRARY_RELEASE AND DIRECTXTK_LIBRARY_DEBUG)
	set ( DIRECTXTK_FOUND TRUE )
else ()
	set ( DIRECTXTK_FOUND FALSE )
endif ()
    
if (DIRECTXTK_FOUND)

    mark_as_advanced ( DIRECTXTK_ROOT DIRECTXTK_LIBRARY_RELEASE DIRECTXTK_LIBRARY_DEBUG )
	
    set ( DIRECTXTK_INCLUDE_DIR ${DIRECTXTK_ROOT}/Inc CACHE STRING "" )
    set ( DIRECTXTK_LIBRARY optimized ${DIRECTXTK_LIBRARY_RELEASE} debug ${DIRECTXTK_LIBRARY_DEBUG} CACHE STRING "")
	
elseif (DIRECTXTK_FIND_REQUIRED)

	message ( FATAL_ERROR "Could not find DirectXTK" )
	
endif()