if (CMAKE_CL_64)
    set ( DIRECTXTEX_ARCH "x64" )
else()
    set ( DIRECTXTEX_ARCH "Win32" )
endif()

find_path( DIRECTXTEX_ROOT NAMES DirectXTex.h )
    
find_library ( DIRECTXTEX_LIBRARY_RELEASE NAMES DirectXTex PATHS ${DIRECTXTEX_ROOT}/Bin/*/${DIRECTXTEX_ARCH}/Release )
find_library ( DIRECTXTEX_LIBRARY_DEBUG NAMES DirectXTex PATHS ${DIRECTXTEX_ROOT}/Bin/*/${DIRECTXTEX_ARCH}/Debug )
    
if (DIRECTXTEX_LIBRARY_RELEASE AND DIRECTXTEX_LIBRARY_DEBUG)
	set ( DIRECTXTEX_FOUND TRUE )
else ()
	set ( DIRECTXTEX_FOUND FALSE )
endif ()
    
if (DIRECTXTEX_FOUND)

    mark_as_advanced ( DIRECTXTEX_ROOT DIRECTXTEX_LIBRARY_RELEASE DIRECTXTEX_LIBRARY_DEBUG )
	
    set ( DIRECTXTEX_INCLUDE_DIR ${DIRECTXTEX_ROOT} CACHE STRING "" )
    set ( DIRECTXTEX_LIBRARY optimized ${DIRECTXTEX_LIBRARY_RELEASE} debug ${DIRECTXTEX_LIBRARY_DEBUG} CACHE STRING "")
	
elseif (DIRECTXTEX_FIND_REQUIRED)

	message ( FATAL_ERROR "Could not find DirectXTex" )
	
endif()